"""added dates to task

Revision ID: 1d074a07da59
Revises: 6898448d7c98
Create Date: 2023-08-19 23:27:46.714819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d074a07da59'
down_revision = '6898448d7c98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('started', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('finished', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'finished')
    op.drop_column('task', 'started')
    op.drop_column('task', 'created')
    # ### end Alembic commands ###
