"""remove md5

Revision ID: 57e8b396ea52
Revises: b8d3f861fb6c
Create Date: 2023-08-17 20:05:36.036564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e8b396ea52'
down_revision = 'b8d3f861fb6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'md5')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('md5', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
