"""remove storage path from file

Revision ID: 6898448d7c98
Revises: db2156006e9b
Create Date: 2023-08-19 23:08:58.602054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6898448d7c98'
down_revision = 'db2156006e9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'storage_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('storage_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
