"""tweaked rating key uniqueness

Revision ID: d5120d314a4c
Revises: 1d074a07da59
Create Date: 2023-08-20 15:35:51.619037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5120d314a4c'
down_revision = '1d074a07da59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_file_rating_key'), 'file', ['rating_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_rating_key'), table_name='file')
    # ### end Alembic commands ###
